### ISSUE TITLE
Make Pagination Optional

### ISSUE THREAD

**Issue by fruitymedley** [strawberry-graphql/strawberry-sqlalchemy#167]
Currently, pagination is configured for a model automatically if any relationship contains `uselist=True`, as seen in [mapper.py:389](https://github.com/strawberry-graphql/strawberry-sqlalchemy/blob/f9c09a156f91abce4ca814b743f1ea6421ecdeb3/src/strawberry_sqlalchemy_mapper/mapper.py#L389). This seems undesirable as a strict rule, particularly in cases with a one-to-few relationship (think `tire`s on `car`s). Obviously, there are cases where pagination is desirable (such as navigating a e-commerce catalog), so pagination should be toggleable.

## Feature Request Type

- [ ] Core functionality
- [x] Alteration (enhancement/optimization) of existing feature(s)
- [ ] New behavior

## Description

- Add a flag for pagination, which, when `True`, configures the schema using relay pagination for the field, and, when `False`, creates a simple array of objects for the field

**Comment by Ckk3** [comment]
This feature was added in #168
